import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar_Main from "@/components/Navbar_Main";
import { Footer } from "@/components/Footer";
import { Banner } from "@/components/Publicity/Banner";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tropical Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Banner/>

        <Providers>
        <Navbar_Main />
        {children}
        </Providers>
          
        <Footer/>
      </body>
    </html>
  );
}
